#!/bin/sh
#
# @name Quadrotor + Tailsitter
#
# @type VTOL Quad Tailsitter
# @class VTOL
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN7 motor 7
# @output MAIN8 motor 8
#
# @output AUX1 motor 9
# @output AUX2 motor 10
# @output AUX3 motor 11
# @output AUX4 motor 12
# @output AUX5 motor 13
# @output AUX6 motor 14
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#
set VEHICLE_TYPE mc
if [ $AUTOCNF = yes ]
then
	param set NAV_ACC_RAD 2

	param set PWM_AUX_DISARMED 1512
	param set PWM_AUX_MIN 1075
	param set PWM_AUX_MAX 1950
	param set PWM_AUX_RATE 400

	param set PWM_MIN 1075
	param set PWM_MAX 1950
	param set PWM_RATE 400

	param set RTL_DESCEND_ALT 10
	param set RTL_LAND_DELAY 0
	param set RTL_RETURN_ALT 30
fi

param set MC_VP_RPM_MAX 0.6
param set COM_PREARM_MODE 0

param set MC_VP_PITCH_MAX 23
param set MC_VP_PITCH_MIN -13

param set MC_VP_OFFSET_P1  0.13043
param set MC_VP_OFFSET_P2  0.14187
param set MC_VP_OFFSET_P3 -0.02975
param set MC_VP_OFFSET_P4  0.05034



set MIXER quad_x_vp
set MIXER_AUX quad_x_vp

set PWM_OUT 12345678
set PWM_AUX_OUT 1234
